### ISSUE TITLE
Changing avatar's color doesn't effect immediately 

### ISSUE THREAD

**Issue by SvetaMemphis** [Memphis-OS/memphis-ui#139]
I changed root's avatar to yellow. It still appears purple at the sidebar and overview page.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/74717402/169666781-ebd11d4a-c5bc-4119-bb7c-95cd3dbeb1b9.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/74717402/169666792-408e0beb-9f17-4171-89d8-c6ea487d34f4.png">

**Comment by avrhamNeeman** [comment]
Update avatar bug fixed
