### ISSUE TITLE
Avg message size

### ISSUE THREAD

**Issue by idanasulinmemphis** [Memphis-OS/memphis-ui#149]
![Screen Shot 2022-05-29 at 11 55 09](https://user-images.githubusercontent.com/74712806/170860180-b7d3a34d-0d1b-406a-9995-413d3c9b4ae1.png)

control plane returns bytes count, please convert it to KB or MB when needed and add the units to the UI

**Comment by avrhamNeeman** [comment]
Done! Thanks.
The average value will convert to the correct units.
