### ISSUE TITLE
Visual enhancements

### ISSUE THREAD

**Issue by idanasulinmemphis** [Memphis-OS/memphis-ui#167]
![Screen Shot 2022-05-31 at 15 08 08](https://user-images.githubusercontent.com/74712806/171169571-5d04be01-e3c8-4f1a-903d-ab310613dd40.png)

pod name -> component

![Screen Shot 2022-05-31 at 15 10 45](https://user-images.githubusercontent.com/74712806/171170091-00f4d1b6-395b-4fc5-9e23-4789a7ec0eaf.png)
too many space after the h1

![Screen Shot 2022-05-31 at 15 11 35](https://user-images.githubusercontent.com/74712806/171170287-dd5b2ee3-9d7e-442d-b7c1-140d1538705e.png)
too many spaces between the components

![Screen Shot 2022-05-31 at 15 12 01](https://user-images.githubusercontent.com/74712806/171170353-c5c4521d-3d40-44f9-ab65-4ff33b740134.png)
h1 and tabs are too closed

**Comment by avrhamNeeman** [comment]
All the issue above was fixed, thanks!
